# ---------- Base image ----------
FROM node:20-slim AS builder

WORKDIR /app

# Disable Turbopack
ENV NEXT_PRIVATE_TURBOPACK=0
ENV TURBOPACK=0
# Next build + TypeScript typecheck can easily exceed 512MB heap.
# Keep it higher in builder to avoid OOM during `next build`.
ENV NODE_OPTIONS="--max-old-space-size=1024"

# Install system deps (openssl for prisma)
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

# Install deps
COPY package*.json ./
RUN npm ci --no-audit --prefer-offline

# Copy source
COPY . .

# # Generate Prisma client
# RUN npx prisma generate

# Build Next.js using Webpack
RUN NEXT_PRIVATE_TURBOPACK=0 TURBOPACK=0 npm run build


# ---------- Production image ----------
FROM node:20-slim AS runner

WORKDIR /app

ENV NEXT_PRIVATE_TURBOPACK=0
ENV TURBOPACK=0
ENV NODE_OPTIONS="--max-old-space-size=256"
ENV NEXT_DISABLE_SOURCEMAPS=1

# Install openssl for prisma runtime
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

# Copy files generated by builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
# COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["npm", "start"]
